import asyncio
import os

from pyrogram import Client
from ..clear_screen import clean



def edit_file(session):
    fil = open("MemBot/StringGen/sessions.txt", "r").read()
    f2 = eval(fil)
    if session in f2:return
    f2.append(session)
    f3 = open("MemBot/StringGen/sessions.txt", "w")
    f3.write(f2.__str__())
    f3.close()

def del_session(session):
    fil = open("MemBot/StringGen/sessions.txt", "r").read()
    f2 = eval(fil)
    f2.remove(session)
    f3 = open("MemBot/StringGen/sessions.txt", "w")
    f3.write(f2.__str__())
    f3.close()
    print("Deleted")


def edd():
    xd = input("How many sessions? :")
    for i in range(int(xd)):
        x1 = input("Give session: ")
        edit_file(x1)
    os.system("clear")
    exit(os.system("python -m MemBot"))

async def generate_session():
    what_to = input("What do you want to do? login or add session,\n\n1: Session, 2: Login: ")
    if int(what_to)==1:
        edd()
    how_many = int(input("How many numbers do you want to login?: "))
    for _ in range(how_many):
        API_ID = 19500615
        API_HASH = "7ee1d55d072add75a01e617fc0cef635"
        try:
            os.remove("MemBot/my_bot.session")
        except:
            pass
        i = Client("my_bot", api_id=API_ID, api_hash=API_HASH, app_version="CoderX", device_model="CoderX's Nokia", system_version="69")
        await i.start()
        ss = await i.export_session_string()
        xx = f"Here is your string session, remember not to share it as it may give access to someone else without your approval.\n\n`{ss}`\n\nGenerated by @CoderX"
        ok = await i.send_message("me", xx)
        edit_file(ss)
        await i.stop()
        clean()
